# BMSProxyCore Configuration
# Main configuration file for module management and global settings

# Module Configuration
# Enable or disable specific modules
modules:
  staffchat:
    enabled: true
  private_messages:
    enabled: true
  lobby_command:
    enabled: true

# Global Messages
# These messages are used across all modules
global:
  # Permission messages
  no-permission-message: "&cYou don't have permission to use this command."

  # Admin command messages
  reload-success-message: "&aConfiguration successfully reloaded."
  reload-fail-message: "&cFailed to reload configuration. Check console for errors."

  # Module disabled messages
  module-disabled-message: "&cThis feature is currently disabled."
  module-config-missing: "&cConfiguration file for {module} module is missing."